### ISSUE TITLE
Tests fail on windows

### ISSUE THREAD

**Issue by zsol** [ambv/black#124]
I suspected this had more to do with my git client setup than an actual bug, but since I'm just using the stock GitHub Windows GUI and these files open just fine in notepad, I thought I'd file an issue here.

The problem is caused by these characters: https://github.com/ambv/black/blob/master/tests/expression.py#L138-L139

```
ERROR: test_expression_diff (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\zsolz\documents\github\black\tests\test_black.py", line 165, in test_expression_diff
    tmp_file = Path(black.dump_to_file(source))
  File "c:\users\zsolz\documents\github\black\black.py", line 2161, in dump_to_file
    f.write(lines)
  File "C:\Users\zsolz\.virtualenvs\black-TlIYXM7K\lib\tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
  File "C:\Users\zsolz\.virtualenvs\black-TlIYXM7K\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 4011: character maps to <undefined>
```

```
ERROR: test_expression_ff (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\zsolz\documents\github\black\tests\test_black.py", line 150, in test_expression_ff
    tmp_file = Path(black.dump_to_file(source))
  File "c:\users\zsolz\documents\github\black\black.py", line 2161, in dump_to_file
    f.write(lines)
  File "C:\Users\zsolz\.virtualenvs\black-TlIYXM7K\lib\tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
  File "C:\Users\zsolz\.virtualenvs\black-TlIYXM7K\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 4011: character maps to <undefined>
```

**Comment by ambv** [comment]
Oh, we just need to make `dump_to_file()` explicitly open files with 'utf8' encoding instead of the default `cp1252` on Windows O_o
