### ISSUE TITLE
Long inline comment on condition statement with braces and and in statement results in unexpected error.

### ISSUE THREAD

**Issue by meshantz** [ambv/black#173]
Operating system: Ubuntu 16.04
Python version: Python 3.6.5
Black version: 18.4a3
Does also happen on master: yes at revision 1445bea97

    if x["id"] in yyyyyyyyyyyyy:  # xxxxxxxx xxxxxxx xxxxxxxxxx xxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        pass

Results in an unclear error message:
    error: cannot format /path/to/file/to/format.py: (-1, 10)

Traced this back to where it is originally raised, but I don't have enough context to troubleshoot further at this point:

    Traceback (most recent call last):
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/bin/black", line 11, in <module>
        sys.exit(main())
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 201, in main
        reformat_one(sources[0], line_length, fast, write_back, report)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 244, in reformat_one
        src, line_length=line_length, fast=fast, write_back=write_back
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 336, in format_file_in_place
        src_contents, line_length=line_length, fast=fast
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 396, in format_file_contents
        dst_contents = format_str(src_contents, line_length=line_length)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 424, in format_str
        for line in split_line(current_line, line_length=line_length, py36=py36):
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 1733, in split_line
        split_line(l, line_length=line_length, inner=True, py36=py36)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 1728, in split_line
        for l in split_func(line, py36):
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 1823, in right_hand_split
        result.append(leaf, preformatted=True)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 731, in append
        self.bracket_tracker.mark(leaf)
      File "/home/mshantz/.virtualenvs/tmp-f7a837d7b440787/lib/python3.6/site-packages/black.py", line 627, in mark
        opening_bracket = self.bracket_match.pop((self.depth, leaf.type))

For reference, these similar statements format fine:

    # one character less on yyy variable
    if x["id"] in yyyyyyyyyyyy:  # xxxxxxxx xxxxxxx xxxxxxxxxx xxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        pass
    # equality instead of contains
    if x["id"] == yyyyyyyyyyyyy:  # xxxxxxxx xxxxxxx xxxxxxxxxx xxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        pass

**Comment by ambv** [comment]
Thanks for the report! Will fix.

**Comment by ambv** [comment]
This was fixed in 18.5b0.

**Comment by meshantz** [comment]
Great! Thanks.
