### ISSUE TITLE
tests/stub.pyi is missing from black-18.5b0.tar.gz

### ISSUE THREAD

**Issue by tiran** [ambv/black#221]
Tests are failing because the stub file is not in the source distro

```
======================================================================
ERROR: test_stub (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/heimes/redhat/fedora-rpms/python-black/black-18.5b0/tests/test_black.py", line 345, in test_stub
    source, expected = read_data("stub.pyi")
  File "/home/heimes/redhat/fedora-rpms/python-black/black-18.5b0/tests/test_black.py", line 38, in read_data
    with open(THIS_DIR / name, "r", encoding="utf8") as test:
FileNotFoundError: [Errno 2] No such file or directory: '/home/heimes/redhat/fedora-rpms/python-black/black-18.5b0/tests/stub.pyi'

----------------------------------------------------------------------
Ran 50 tests in 7.656s

FAILED (errors=1)

```

**Comment by tiran** [comment]
@ambv The missing file breaks Fedora packaging. Could you role another release with PR #222, please?

**Comment by ambv** [comment]
@tiran, could that wait until Monday? I'd like to pace releases a bit so every update is worthwhile.

**Comment by tiran** [comment]
@ambv Of course! There is no need to rush a new release at all. Please take your time, decompress from PyCon, and enjoy the weekend with your family.
