### ISSUE TITLE
platform lacks a functioning sem_open implementation

### ISSUE THREAD

**Issue by neko404notfound** [ambv/black#388]
Hi!

Cannot seem to run Black. Something about lack of SemLock implementation.

Included the tb I get when running; and the unit test output.

Operating system: Android 8.0/Termux ARM -- `Linux localhost 3.18.66-perf+ #1 SMP PREEMPT Thu May 17 17:00:18 CST 2018 aarch64 Android`
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master:

Traceback:
```py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/synchronize.py", line 29, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/libneko/.venv/bin/black", line 11, in <module>
    load_entry_point('black', 'console_scripts', 'black')()
  File "/data/data/com.termux/files/home/libneko/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/home/libneko/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/home/libneko/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/home/libneko/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/data/data/com.termux/files/home/libneko/.venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/data/com.termux/files/home/black/black.py", line 341, in main
    executor = ProcessPoolExecutor(max_workers=os.cpu_count())
  File "/data/data/com.termux/files/usr/lib/python3.6/concurrent/futures/process.py", line 402, in __init__
    EXTRA_QUEUED_CALLS)
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/context.py", line 66, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/synchronize.py", line 34, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

Unit tests:
```py
running test
running egg_info
writing black.egg-info/PKG-INFO
writing dependency_links to black.egg-info/dependency_links.txt
writing entry points to black.egg-info/entry_points.txt
writing requirements to black.egg-info/requires.txt
writing top-level names to black.egg-info/top_level.txt
reading manifest file 'black.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
/data/data/com.termux/files/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
warning: no files found matching '*.rst'
warning: no files found matching '*.txt' under directory 'tests'
writing manifest file 'black.egg-info/SOURCES.txt'
running build_ext
test_assertFormatEqual (tests.test_black.BlackTestCase) ... ok
test_assert_equivalent_different_asts (tests.test_black.BlackTestCase) ... ok
test_black (tests.test_black.BlackTestCase) ... ok
test_broken_symlink (tests.test_black.BlackTestCase) ... ok
test_cache_broken_file (tests.test_black.BlackTestCase) ... ok
test_cache_multiple_files (tests.test_black.BlackTestCase) ... ok
test_cache_single_file_already_cached (tests.test_black.BlackTestCase) ... ok
test_cantfit (tests.test_black.BlackTestCase) ... ok
test_check_diff_use_together (tests.test_black.BlackTestCase) ... FAIL
test_comments (tests.test_black.BlackTestCase) ... ok
test_comments2 (tests.test_black.BlackTestCase) ... ok
test_comments3 (tests.test_black.BlackTestCase) ... ok
test_comments4 (tests.test_black.BlackTestCase) ... ok
test_comments5 (tests.test_black.BlackTestCase) ... ok
test_composition (tests.test_black.BlackTestCase) ... ok
test_debug_visitor (tests.test_black.BlackTestCase) ... ok
test_empty (tests.test_black.BlackTestCase) ... ok
test_empty_exclude (tests.test_black.BlackTestCase) ... ok
test_empty_ff (tests.test_black.BlackTestCase) ... ok
test_empty_include (tests.test_black.BlackTestCase) ... ok
test_empty_lines (tests.test_black.BlackTestCase) ... ok
test_endmarker (tests.test_black.BlackTestCase) ... ok
test_expression (tests.test_black.BlackTestCase) ... /data/data/com.termux/files/usr/lib/python3.6/asyncio/base_events.py:511: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  source=self)
ok
test_expression_diff (tests.test_black.BlackTestCase) ... ok
test_expression_ff (tests.test_black.BlackTestCase) ... ok
test_failed_formatting_does_not_get_cached (tests.test_black.BlackTestCase) ... ok
test_filter_cached (tests.test_black.BlackTestCase) ... ok
test_fmtonoff (tests.test_black.BlackTestCase) ... ok
test_fmtonoff2 (tests.test_black.BlackTestCase) ... ok
test_format_file_contents (tests.test_black.BlackTestCase) ... ok
test_fstring (tests.test_black.BlackTestCase) ... ok
test_function (tests.test_black.BlackTestCase) ... ok
test_function2 (tests.test_black.BlackTestCase) ... ok
test_get_future_imports (tests.test_black.BlackTestCase) ... ok
test_import_spacing (tests.test_black.BlackTestCase) ... ok
test_include_exclude (tests.test_black.BlackTestCase) ... ok
test_invalid_include_exclude (tests.test_black.BlackTestCase) ... ok
test_is_python36 (tests.test_black.BlackTestCase) ... ok
test_multi_file_force_py36 (tests.test_black.BlackTestCase) ... FAIL
test_multi_file_force_pyi (tests.test_black.BlackTestCase) ... FAIL
test_new_line_between_class_and_code (tests.test_black.BlackTestCase) ... ok
test_no_cache_when_stdin (tests.test_black.BlackTestCase) ... ok
test_no_cache_when_writeback_diff (tests.test_black.BlackTestCase) ... ok
test_no_files (tests.test_black.BlackTestCase) ... ok
test_pipe_force_py36 (tests.test_black.BlackTestCase) ... ok
test_pipe_force_pyi (tests.test_black.BlackTestCase) ... ok
test_piping (tests.test_black.BlackTestCase) ... ok
test_piping_diff (tests.test_black.BlackTestCase) ... ok
test_preserves_line_endings (tests.test_black.BlackTestCase) ... ok
test_python2 (tests.test_black.BlackTestCase) ... ok
test_python2_unicode_literals (tests.test_black.BlackTestCase) ... ok
test_read_cache_line_lengths (tests.test_black.BlackTestCase) ... ok
test_read_cache_no_cachefile (tests.test_black.BlackTestCase) ... ok
test_remove_empty_parentheses_after_class (tests.test_black.BlackTestCase) ... ok
test_report_normal (tests.test_black.BlackTestCase) ... ok
test_report_quiet (tests.test_black.BlackTestCase) ... ok
test_report_verbose (tests.test_black.BlackTestCase) ... ok
test_self (tests.test_black.BlackTestCase) ... ok
test_setup (tests.test_black.BlackTestCase) ... ok
test_shhh_click (tests.test_black.BlackTestCase) ... ERROR
test_single_file_force_py36 (tests.test_black.BlackTestCase) ... ok
test_single_file_force_pyi (tests.test_black.BlackTestCase) ... ok
test_slices (tests.test_black.BlackTestCase) ... ok
test_string_prefixes (tests.test_black.BlackTestCase) ... ok
test_string_quotes (tests.test_black.BlackTestCase) ... ok
test_stub (tests.test_black.BlackTestCase) ... ok
test_symlink_out_of_root_directory (tests.test_black.BlackTestCase) ... ok
test_write_cache_creates_directory_if_needed (tests.test_black.BlackTestCase) ... ok
test_write_cache_read_cache (tests.test_black.BlackTestCase) ... ok
test_write_cache_write_fail (tests.test_black.BlackTestCase) ... ok

======================================================================
ERROR: test_shhh_click (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/black/tests/test_black.py", line 1213, in test_shhh_click
    _unicodefun._verify_python3_env()
  File "/data/data/com.termux/files/home/libneko/.venv/lib/python3.6/site-packages/click/_unicodefun.py", line 64, in _verify_python3_env
    stderr=subprocess.PIPE).communicate()[0]
  File "/data/data/com.termux/files/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/data/data/com.termux/files/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'locale': 'locale'

======================================================================
FAIL: test_check_diff_use_together (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/data/com.termux/files/home/black/tests/test_black.py", line 954, in test_check_diff_use_together
    self.assertEqual(result.exit_code, 1, result.output)
AssertionError: -1 != 1 : 

======================================================================
FAIL: test_multi_file_force_py36 (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/data/com.termux/files/home/black/tests/test_black.py", line 1070, in test_multi_file_force_py36
    self.assertEqual(result.exit_code, 0)
AssertionError: -1 != 0

======================================================================
FAIL: test_multi_file_force_pyi (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/data/com.termux/files/home/black/tests/test_black.py", line 1016, in test_multi_file_force_pyi
    self.assertEqual(result.exit_code, 0)
AssertionError: -1 != 0

----------------------------------------------------------------------
Ran 70 tests in 52.816s

FAILED (failures=3, errors=1)
Test failed: <unittest.runner.TextTestResult run=70 errors=1 failures=3>
error: Test failed: <unittest.runner.TextTestResult run=70 errors=1 failures=3>
```

Hope this is of some help.

**Comment by carljm** [comment]
Hi, thanks for the report! I don’t think this is a Black issue, it seems like the platform you are running Python on is missing some functionality required by the Python multiprocessing module. This would probably be something to bring to the attention of the maintainers of your Python build for that platform.
