### ISSUE TITLE
"pip show black" results in UnicodeEncodeError

### ISSUE THREAD

**Issue by sandeepbhat** [ambv/black#411]
Running `pip show black` results in error. `black` is installed using the `pip install black`.

```
$ pip install black
...
...
Installing collected packages: attrs, toml, appdirs, click, black
Successfully installed appdirs-1.4.3 attrs-18.1.0 black-18.6b4 click-6.7 toml-0.9.4
```

#### `pip show` output
```
Name: black
Version: 18.6b4
Summary: The uncompromising code formatter.
Home-page: https://github.com/ambv/black
Author-email: lukasz@langa.pl
License: MIT
Location: c:\users\sanbha\appdata\local\programs\python\python36\lib\site-packages
Requires: appdirs, toml, click, attrs
Required-by:
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\logging\__init__.py", line 995, in emit
    stream.write(msg)
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0141' in position 8: character maps to <undefined>
Call stack:
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sanbha\AppData\Local\Programs\Python\Python36\Scripts\pip.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\__init__.py", line 246, in main
    return command.main(cmd_args)
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\commands\show.py", line 43, in run
    results, list_files=options.files, verbose=options.verbose):
  File "c:\users\sanbha\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\commands\show.py", line 141, in print_results
    logger.info("Author: %s", dist.get('author', ''))
Message: 'Author: %s'
Arguments: ('\u0141ukasz Langa',)
```
#### Environment
Operating system: Windows 10 Enterprise
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: No

**Comment by JelleZijlstra** [comment]
That seems like a pip bug, not a black bug.

**Comment by zsol** [comment]
Yep, see https://github.com/ambv/black/pull/352 for more context. This is a bug in pip on Windows. Is this causing any problems for you @sandeepbhat?

**Comment by sandeepbhat** [comment]
@zsol It is not causing any problems for me. I was just working on automating some stuff and `pip show` keeps throwing the error. I can workaround this until it is fixed from `pip`.

Sorry for the false alarm. I will be more careful and thorough if raise a bug in the future :)

**Comment by zsol** [comment]
No worries :)
