### ISSUE TITLE
OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by codingjoe** [ambv/black#421]
### system

Operating system: Amazon Linux
Python version: 3.6
*Black* version: black==18.6b3
Does also happen on master: yes

### description

Hey there,

is there a way to disable multiprocessing? I am running black on a system that doesn't support multiprocessing (as it doesn't support process synchronization). More specifically I am running this on AWS lambda. Ref https://github.com/LambdaLint/black/issues/5

I do like the default, but it would be great to define your own process pool size to optimize performance or in my case disable it completely.

Of course the problem is here:
https://github.com/ambv/black/blob/e94a41f92a568706700522aaad48ebd137fe1d8b/black.py#L342

### solution proposal

I would be willing to provide a patch if you agree that this should be fixed. My proposal would be to add a `--job/-j` argument, that defaults to `os.cpu_count()`. If set to 1 it would not use a process pool but run sequentially. That would solve the issue for all virtual or embedded systems that don't provide processes synchronization.

### stack trace

```
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/var/lang/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/task/black.py", line 3511, in <module>
    main()
  File "/var/task/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/task/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/task/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/task/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/task/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/task/black.py", line 341, in main
    executor = ProcessPoolExecutor(max_workers=os.cpu_count())
  File "/var/lang/lib/python3.6/concurrent/futures/process.py", line 390, in __init__
    EXTRA_QUEUED_CALLS)
  File "/var/lang/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/var/lang/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.6/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
OSError: [Errno 38] Function not implemented
```

**Comment by zsol** [comment]
You can work around this by calling black with a single file, instead of the whole directory.

About fixing this in black: I don't think just setting the worker count to 1 will work, all the relevant multiprocessing code will still be called. Any alternative implementations I can think of (without using the multiprocessing primitives) will be either complicated or inefficient, so I'm not sure how to solve this in black without a lot of effort.

Anyway, this is deliberate behavior on black's part, and unless we can come up with a reasonable solution, I don't think it's going to change. Going to leave this open for a while to gather some ideas, though.

**Comment by codingjoe** [comment]
@zsol I figured something like this, which is why I didn't provide a patch right away. I hope the single file behavior remains the same then.

Little side note, the file tree walker (which it isn't really) could be moved into a consumer-producer pattern on asyncio. Where the tree walker is a producer. This will mean that you can start executing the linter on files before the whole tree is read. Very off topic tho.
