### ISSUE TITLE
bug(formatting): formatting inside braces and brackets on Windows

### ISSUE THREAD

**Issue by Kristinita** [ambv/black#495]
### 1. Summary

Black ugly formats code between {braces} and (parentheses) on Windows.

This was the reason why I didn't use Black in my code. But I try online formatter and get different result.

### 2. Data

Is not a working code, this is examples, that Black incorrect format on my machine.

+ `kira__demo__black.py`:

```python
SITEMAP = {
    'format': 'xml',
    'priorities': {
        'articles': 1,
        'indexes': 0.5,
        'pages': 0.5
    },
    'changefreqs': {
        'articles': 'always',
        'indexes': 'weekly',
        'pages': 'always'
    }
}


def pyfancy_critical(pyfancy_variable):
    """Critical level."""
    pyfancy_function(
        logger_function().critical,
        pyfancy().red_bg().bold(),
        pyfancy_variable)


def logger_function():
    return logbook.Logger(os.path.splitext(
        os.path.basename(traceback.extract_stack()[-3].filename))[0])


def eric_head(head_metadata):
    for filename_pylint in files_loop():
        if head_metadata in open(filename_pylint, encoding='utf-8').read():
            pyfancy_debug(
                '«' +
                head_metadata +
                '» contains in ' +
                filename_pylint)
        else:
            pyfancy_error(
                filename_pylint +
                ' not contains «' +
                head_metadata + '»')
            yield False

```

### 3. Expected behavior

[**As in online formatter**](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ASIAeVdAD2IimZxl1N_WkVym1IshEZ_jhrwXo6Cwl46lz4XNFi-N352CdFYdlBo2CBQXO6sZCs3WKoDWFltXglbfgMpZUn2YCnWOp0mr_NnUUSvs9fky_EP8-HIH6GcHIbobmy-wkfPRod8WrUl_GWaqrjdg_ICihL6E7pNum9KH5wGH2XXHoh0bIlldOQTGFlS7-LMCM0NHxlKzT6q1oVkn72ZxjE1lUY4zvJ_dzBZv2AhcJYMbU89vOGjEVtBF71egjlaExLqBS4vjARRjBUYpR7wVN7J4RiuTBf2HGTNrdkfh3bkJkGKkoMmRqkRkfX-NSxIvBalLFZxYAL_1Izhx8Yvp6OexEj5jR0B32PD1ls8JMuQXexcaH7pdSdSjHBlFRWL8GfFe4Z1EVt7XPt683dfsnDrteLlDnyUCiih-virZQmMCpeRHYR59RApox2MlUu4Nsu2i-st_GFalM1inXMtMJLXO81C5-NdxzbaZKDKNfeOwE42cv6Li9yTEVRmG33z1tQZ53pTsDjwVJoPyT5u0Iv784zKjqHU67grrVjLffOEdfiMomtsyjzH1bs4PrXqfgIsFK-Td3bRKyp3cGVufoq9eOxuh3rHq6uslhKpeoxO0ld9x6Dbsd9ZdeCthkjYzugCofwAAAAAAJGH99PoKqAVAAGBBIkJAABed7l8scRn-wIAAAAABFla):

```python
SITEMAP = {
    "format": "xml",
    "priorities": {
        "articles": 1,
        "indexes": 0.5,
        "pages": 0.5,
    },
    "changefreqs": {
        "articles": "always",
        "indexes": "weekly",
        "pages": "always",
    },
}


def pyfancy_critical(pyfancy_variable):
    """Critical level."""
    pyfancy_function(
        logger_function().critical,
        pyfancy().red_bg().bold(),
        pyfancy_variable,
    )


def logger_function():
    return logbook.Logger(
        os.path.splitext(
            os.path.basename(
                traceback.extract_stack()[-3].filename
            )
        )[0]
    )


def eric_head(head_metadata):
    for filename_pylint in files_loop():
        if (
            head_metadata
            in open(
                filename_pylint, encoding="utf-8"
            ).read()
        ):
            pyfancy_debug(
                "«"
                + head_metadata
                + "» contains in "
                + filename_pylint
            )
        else:
            pyfancy_error(
                filename_pylint
                + " not contains «"
                + head_metadata
                + "»"
            )
            yield False

```

### 4. Actual behavior

On my local machine:

```diff
D:\SashaDebugging\SashaPython>black --diff kira__demo__black.py
--- kira__demo__black.py        2018-09-02 16:57:51.430521 +0000
+++ kira__demo__black.py        2018-09-02 16:58:17.160718 +0000
@@ -1,47 +1,32 @@
 # -*- coding: utf-8 -*-
 # @Author: SashaChernykh
 # @Date: 2018-09-02 15:53:37
 # @Last Modified time: 2018-09-02 19:57:51
 SITEMAP = {
-    'format': 'xml',
-    'priorities': {
-        'articles': 1,
-        'indexes': 0.5,
-        'pages': 0.5
-    },
-    'changefreqs': {
-        'articles': 'always',
-        'indexes': 'weekly',
-        'pages': 'always'
-    }
+    "format": "xml",
+    "priorities": {"articles": 1, "indexes": 0.5, "pages": 0.5},
+    "changefreqs": {"articles": "always", "indexes": "weekly", "pages": "always"},
 }


 def pyfancy_critical(pyfancy_variable):
     """Critical level."""
     pyfancy_function(
-        logger_function().critical,
-        pyfancy().red_bg().bold(),
-        pyfancy_variable)
+        logger_function().critical, pyfancy().red_bg().bold(), pyfancy_variable
+    )


 def logger_function():
-    return logbook.Logger(os.path.splitext(
-        os.path.basename(traceback.extract_stack()[-3].filename))[0])
+    return logbook.Logger(
+        os.path.splitext(os.path.basename(traceback.extract_stack()[-3].filename))[0]
+    )


 def eric_head(head_metadata):
     for filename_pylint in files_loop():
-        if head_metadata in open(filename_pylint, encoding='utf-8').read():
-            pyfancy_debug(
-                '«' +
-                head_metadata +
-                '» contains in ' +
-                filename_pylint)
+        if head_metadata in open(filename_pylint, encoding="utf-8").read():
+            pyfancy_debug("«" + head_metadata + "» contains in " + filename_pylint)
         else:
-            pyfancy_error(
-                filename_pylint +
-                ' not contains «' +
-                head_metadata + '»')
+            pyfancy_error(filename_pylint + " not contains «" + head_metadata + "»")
             yield False

reformatted kira__demo__black.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

### 5. Virtual environment

I reproduce the problem in virtual environment.

3 tests failed → I press <kbd>Ctrl+C</kbd>.

<details>
<summary>
<b>Click here to see full output.</b></summary><br>

```sh
D:\SashaForks>mkvirtualenv kirablackenv
Using base prefix 'c:\\python37'
New python executable in C:\Users\SashaChernykh\Envs\kirablackenv\Scripts\python.exe
Installing setuptools, pip, wheel...done.

(kirablackenv) D:\SashaForks>toggleglobalsitepackages

    Disabled global site-packages
(kirablackenv) D:\SashaForks>hub clone ambv/black
Cloning into 'black'...
remote: Counting objects: 2140, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 2140 (delta 7), reused 14 (delta 7), pack-reused 2120 eceiving objects: 100% (2140/2140), 1.94 MiB | 482.0Receiving objects: 100% (2140/2140), 2.58 MiB | 606.00 KiB/s, done.

Resolving deltas: 100% (1447/1447), done.

(kirablackenv) D:\SashaForks>cd black

(kirablackenv) D:\SashaForks\black>pip install -e .
Obtaining file:///D:/SashaForks/black
  Installing build dependencies ... done
Collecting click>=6.5 (from black==18.6b4)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from black==18.6b4)
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting appdirs (from black==18.6b4)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting toml>=0.9.4 (from black==18.6b4)
  Using cached https://files.pythonhosted.org/packages/f5/f9/044110c267e6408013b85166a7cfcd352cf85275aa8ce700aa5c0eb407ba/toml-0.9.4.tar.gz
Building wheels for collected packages: toml
  Running setup.py bdist_wheel for toml ... done
  Stored in directory: C:\Users\SashaChernykh\AppData\Local\pip\Cache\wheels\60\a0\8a\eaebd461aa0abf3d38546b12f3b3234de0a39de13374dad39e
Successfully built toml
Installing collected packages: click, attrs, appdirs, toml, black
  Running setup.py develop for black
Successfully installed appdirs-1.4.3 attrs-18.2.0 black click-6.7 toml-0.9.4

(kirablackenv) D:\SashaForks\black>python setup.py test
running test
running egg_info
writing black.egg-info\PKG-INFO
writing dependency_links to black.egg-info\dependency_links.txt
writing entry points to black.egg-info\entry_points.txt
writing requirements to black.egg-info\requires.txt
writing top-level names to black.egg-info\top_level.txt
reading manifest file 'black.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst'
warning: no files found matching '*.txt' under directory 'tests'
writing manifest file 'black.egg-info\SOURCES.txt'
running build_ext
test_assertFormatEqual (tests.test_black.BlackTestCase) ... ok
test_assert_equivalent_different_asts (tests.test_black.BlackTestCase) ... ok
test_black (tests.test_black.BlackTestCase) ... ok
test_bracket_match (tests.test_black.BlackTestCase) ... ok
test_broken_symlink (tests.test_black.BlackTestCase) ... ok
test_cache_broken_file (tests.test_black.BlackTestCase) ... ok
test_cache_multiple_files (tests.test_black.BlackTestCase) ... ok
test_cache_single_file_already_cached (tests.test_black.BlackTestCase) ... ok
test_cantfit (tests.test_black.BlackTestCase) ... ok
test_check_diff_use_together (tests.test_black.BlackTestCase) ... running test
running egg_info
writing black.egg-info\PKG-INFO
writing dependency_links to black.egg-info\dependency_links.txt
writing entry points to black.egg-info\entry_points.txt
writing requirements to black.egg-info\requires.txt
writing top-level names to black.egg-info\top_level.txt
reading manifest file 'black.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst'
warning: no files found matching '*.txt' under directory 'tests'
writing manifest file 'black.egg-info\SOURCES.txt'
running build_ext
test_assertFormatEqual (tests.test_black.BlackTestCase) ... ok
test_assert_equivalent_different_asts (tests.test_black.BlackTestCase) ... ok
test_black (tests.test_black.BlackTestCase) ... ok
test_bracket_match (tests.test_black.BlackTestCase) ... ok
test_broken_symlink (tests.test_black.BlackTestCase) ... ok
test_cache_broken_file (tests.test_black.BlackTestCase) ... ok
test_cache_multiple_files (tests.test_black.BlackTestCase) ... ok
test_cache_single_file_already_cached (tests.test_black.BlackTestCase) ... ok
test_cantfit (tests.test_black.BlackTestCase) ... ok
test_check_diff_use_together (tests.test_black.BlackTestCase) ... FAIL
test_comments (tests.test_black.BlackTestCase) ... ok
test_comments2 (tests.test_black.BlackTestCase) ... ok
test_comments3 (tests.test_black.BlackTestCase) ... ok
test_comments4 (tests.test_black.BlackTestCase) ... ok
test_comments5 (tests.test_black.BlackTestCase) ... ok
test_composition (tests.test_black.BlackTestCase) ... ok
test_debug_visitor (tests.test_black.BlackTestCase) ... ok
test_empty (tests.test_black.BlackTestCase) ... ok
test_empty_exclude (tests.test_black.BlackTestCase) ... ok
test_empty_ff (tests.test_black.BlackTestCase) ... ok
test_empty_include (tests.test_black.BlackTestCase) ... ok
test_empty_lines (tests.test_black.BlackTestCase) ... ok
test_endmarker (tests.test_black.BlackTestCase) ... ok
test_expression (tests.test_black.BlackTestCase) ... ok
test_expression_diff (tests.test_black.BlackTestCase) ... ok
test_expression_ff (tests.test_black.BlackTestCase) ... ok
test_failed_formatting_does_not_get_cached (tests.test_black.BlackTestCase) ... ok
test_filter_cached (tests.test_black.BlackTestCase) ... ok
test_fmtonoff (tests.test_black.BlackTestCase) ... ok
test_fmtonoff2 (tests.test_black.BlackTestCase) ... ok
test_format_file_contents (tests.test_black.BlackTestCase) ... ok
test_fstring (tests.test_black.BlackTestCase) ... ok
test_function (tests.test_black.BlackTestCase) ... ok
test_function2 (tests.test_black.BlackTestCase) ... ok
test_get_future_imports (tests.test_black.BlackTestCase) ... ok
test_import_spacing (tests.test_black.BlackTestCase) ... ok
test_include_exclude (tests.test_black.BlackTestCase) ... ok
test_invalid_include_exclude (tests.test_black.BlackTestCase) ... ok
test_is_python36 (tests.test_black.BlackTestCase) ... ok
test_multi_file_force_py36 (tests.test_black.BlackTestCase) ... FAIL
test_multi_file_force_pyi (tests.test_black.BlackTestCase) ... FAIL
test_new_line_between_class_and_code (tests.test_black.BlackTestCase) ... ok
test_no_cache_when_stdin (tests.test_black.BlackTestCase) ... ok
test_no_cache_when_writeback_diff (tests.test_black.BlackTestCase) ... ok
test_no_files (tests.test_black.BlackTestCase) ... ok
test_numeric_literals (tests.test_black.BlackTestCase) ... ok
test_numeric_literals_py2 (tests.test_black.BlackTestCase) ... ok
test_pipe_force_py36 (tests.test_black.BlackTestCase) ... ok
test_pipe_force_pyi (tests.test_black.BlackTestCase) ... ok
test_piping (tests.test_black.BlackTestCase) ... ok
test_piping_diff (tests.test_black.BlackTestCase) ... ok
test_preserves_line_endings (tests.test_black.BlackTestCase) ... ok
test_preserves_line_endings_via_stdin (tests.test_black.BlackTestCase) ... ok
test_python2 (tests.test_black.BlackTestCase) ... ok
test_python2_unicode_literals (tests.test_black.BlackTestCase) ... ok
test_python37 (tests.test_black.BlackTestCase) ... ok
test_read_cache_line_lengths (tests.test_black.BlackTestCase) ... ok
test_read_cache_no_cachefile (tests.test_black.BlackTestCase) ... ok
test_remove_empty_parentheses_after_class (tests.test_black.BlackTestCase) ... ok
test_report_normal (tests.test_black.BlackTestCase) ... ok
test_report_quiet (tests.test_black.BlackTestCase) ... ok
test_report_verbose (tests.test_black.BlackTestCase) ... ok
test_self (tests.test_black.BlackTestCase) ... ok
test_setup (tests.test_black.BlackTestCase) ... ok
test_shhh_click (tests.test_black.BlackTestCase) ... ok
test_single_file_force_py36 (tests.test_black.BlackTestCase) ... ok
test_single_file_force_pyi (tests.test_black.BlackTestCase) ... ok
test_slices (tests.test_black.BlackTestCase) ... ok
test_string_prefixes (tests.test_black.BlackTestCase) ... ok
test_string_quotes (tests.test_black.BlackTestCase) ... ok
test_stub (tests.test_black.BlackTestCase) ... ok
test_symlink_out_of_root_directory (tests.test_black.BlackTestCase) ... ok
test_write_cache_creates_directory_if_needed (tests.test_black.BlackTestCase) ... ok
test_write_cache_read_cache (tests.test_black.BlackTestCase) ... ok
test_write_cache_write_fail (tests.test_black.BlackTestCase) ... ok

======================================================================
FAIL: test_check_diff_use_together (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python37\Lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "d:\sashaforks\black\tests\test_black.py", line 1005, in test_check_diff_use_together
    self.assertEqual(result.exit_code, 1, result.output)
AssertionError: -1 != 1 :

======================================================================
FAIL: test_multi_file_force_py36 (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python37\Lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "d:\sashaforks\black\tests\test_black.py", line 1123, in test_multi_file_force_py36
    self.assertEqual(result.exit_code, 0)
AssertionError: -1 != 0

======================================================================
FAIL: test_multi_file_force_pyi (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python37\Lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "d:\sashaforks\black\tests\test_black.py", line 1067, in test_multi_file_force_pyi
    self.assertEqual(result.exit_code, 0)
AssertionError: -1 != 0

----------------------------------------------------------------------
Ran 75 tests in 11.365s

FAILED (failures=3)
Test failed: <unittest.runner.TextTestResult run=75 errors=0 failures=3>
error: Test failed: <unittest.runner.TextTestResult run=75 errors=0 failures=3>

(kirablackenv) D:\SashaDebugging\SashaPython>black --diff kira__demo__black.py
--- kira__demo__black.py        2018-09-02 16:57:51.430521 +0000
+++ kira__demo__black.py        2018-09-02 17:16:35.280453 +0000
@@ -1,47 +1,32 @@
 # -*- coding: utf-8 -*-
 # @Author: SashaChernykh
 # @Date: 2018-09-02 15:53:37
 # @Last Modified time: 2018-09-02 19:57:51
 SITEMAP = {
-    'format': 'xml',
-    'priorities': {
-        'articles': 1,
-        'indexes': 0.5,
-        'pages': 0.5
-    },
-    'changefreqs': {
-        'articles': 'always',
-        'indexes': 'weekly',
-        'pages': 'always'
-    }
+    "format": "xml",
+    "priorities": {"articles": 1, "indexes": 0.5, "pages": 0.5},
+    "changefreqs": {"articles": "always", "indexes": "weekly", "pages": "always"},
 }


 def pyfancy_critical(pyfancy_variable):
     """Critical level."""
     pyfancy_function(
-        logger_function().critical,
-        pyfancy().red_bg().bold(),
-        pyfancy_variable)
+        logger_function().critical, pyfancy().red_bg().bold(), pyfancy_variable
+    )


 def logger_function():
-    return logbook.Logger(os.path.splitext(
-        os.path.basename(traceback.extract_stack()[-3].filename))[0])
+    return logbook.Logger(
+        os.path.splitext(os.path.basename(traceback.extract_stack()[-3].filename))[0]
+    )


 def eric_head(head_metadata):
     for filename_pylint in files_loop():
-        if head_metadata in open(filename_pylint, encoding='utf-8').read():
-            pyfancy_debug(
-                '«' +
-                head_metadata +
-                '» contains in ' +
-                filename_pylint)
+        if head_metadata in open(filename_pylint, encoding="utf-8").read():
+            pyfancy_debug("«" + head_metadata + "» contains in " + filename_pylint)
         else:
-            pyfancy_error(
-                filename_pylint +
-                ' not contains «' +
-                head_metadata + '»')
+            pyfancy_error(filename_pylint + " not contains «" + head_metadata + "»")
             yield False

reformatted kira__demo__black.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

</details><br>

### 6. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.7.0,
+ Black 18.6b4,
+ virtualenv 16.0.0,
+ virtualenvwrapper-win 1.2.5.

Thanks.

**Comment by JelleZijlstra** [comment]
Sounds like a difference in the `--line-length` configuration option. Black will put the dictionary on one line if it fits within the line length (88 chars by default).
