### ISSUE TITLE
Consider where "point/cursor" should end up

### ISSUE THREAD

**Issue by kootenpv** [ambv/black#516]
Maybe it could be a nice addition when it becomes possible to add "cursor_position" and then black could return where it should end up after processing

**Comment by kootenpv** [comment]
@ambv It counts for _any_ editor plugin.

**Comment by ambv** [comment]
Oh, you'd want `black` the command to accept `--cursor-line=` and `--cursor-column=` arguments and return new ones with the output?

**Comment by kootenpv** [comment]
@ambv Exactly! Given that it uses the AST, it should be possible to implement.

**Comment by vastus** [comment]
Maybe the vim plugin could use this information as well. Currently the plugin errors if the cursor is at EOF and reformatting cuts down on the lines produced.

Here's an example (`|` denotes cursor position):

in:

```
[
    42
]|
```

running `:Black` produces the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 76, in Black
vim.error: cursor position outside buffer
```

after hitting return:

```
|[42]
```
