### ISSUE TITLE
Update attrs dependency from 17.4.0 please

### ISSUE THREAD

**Issue by ashwinvis** [ambv/black#539]
Operating system: Arch Linux
Python version: 3.7.0
*Black* version: 18.9b0
Does also happen on master: Yes.

Do note that that there is no issue with latest `attrs==18.2.0`. The following occurs with `attrs==17.4.0`.

```python
Error detected while processing /home/avmo/.vim/plugged/black/plugin/black.vim:
line  124:
Traceback (most recent call last):
  File "<string>", line 56, in <module>
  File "/home/avmo/.local/lib/python3.7/site-packages/black.py", line 39, in <module>
    from attr import dataclass, Factory
  File "/home/avmo/.local/lib/python3.7/site-packages/attr/__init__.py", line 5, in <module>
    from . import converters, exceptions, filters, validators
  File "/home/avmo/.local/lib/python3.7/site-packages/attr/filters.py", line 7, in <module>
    from ._compat import isclass
  File "/home/avmo/.local/lib/python3.7/site-packages/attr/_compat.py", line 139, in <module>
    set_closure_cell = make_set_closure_cell()
  File "/home/avmo/.local/lib/python3.7/site-packages/attr/_compat.py", line 131, in make_set_closure_cell
    set_closure_cell = ctypes.pythonapi.PyCell_Set
  File "/usr/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: vim: undefined symbol: PyCell_Set
```

**Comment by ambv** [comment]
Thanks for your report! ✨ 🍰 ✨
