### ISSUE TITLE
blackd appears to fail tests with a slightly longer body

### ISSUE THREAD

**Issue by tuchandra** [ambv/black#628]
I ran into this while trying to write a PR for #622. If I add this test to `tests/test_black.py` (I put it at line 1351, but it shouldn't matter), it fails:

```
    @unittest.skipUnless(has_blackd_deps, "blackd's dependencies are not installed")
    @async_test
    async def test_blackd_long_body(self) -> None:
        app = blackd.make_app()
        async with TestClient(TestServer(app)) as client:
            response = await client.post("/", data=b'print("hello a very long world")\n')
            self.assertEqual(response.status, 204)
            self.assertEqual(await response.read(), b"")
```

Scrolling way up to the error, here it is:
```
======================================================================
FAIL: test_self (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/miniconda3/envs/black-dev/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/Users/chtu8001/Work/black/tests/test_black.py", line 181, in test_self
    self.assertFormatEqual(expected, actual)
  File "/Users/chtu8001/Work/black/tests/test_black.py", line 156, in assertFormatEqual
    self.assertEqual(expected, actual)
AssertionError: '#!/u[58639 chars]post("/", data=b\'print("hello a very long wor[6606 chars]")\n' != '#!/u[58639 chars]post(\n                "/", data=b\'print("hel[6638 chars]")\n'
```

This one, which is already in the test suite, passes:

```
    @unittest.skipUnless(has_blackd_deps, "blackd's dependencies are not installed")
    @async_test
    async def test_blackd_request_no_change(self) -> None:
        app = blackd.make_app()
        async with TestClient(TestServer(app)) as client:
            response = await client.post("/", data=b'print("hello world")\n')
            self.assertEqual(response.status, 204)
            self.assertEqual(await response.read(), b"")
```

Using `data=b'print("hello long world123456")\n'` passes, but `data=b'print("hello long world1234567")\n'` fails. The former is 31 characters plus the newline; the latter is 32.

I can't come up with any reason that this is happening. Any thoughts?

Operating system: MacOS 10.13.6, High Sierra
Python version: 3.6.7
*Black* (and *blackd*) version: 18.9b0
Does also happen on master: yes

**Comment by JelleZijlstra** [comment]
I think it's because you made the file poorly formatted (the line is too long). Try running black on test_black.py first.

**Comment by tuchandra** [comment]
That was it, thank you!
