### ISSUE TITLE
ModuleNotFoundError: No module named 'black'

### ISSUE THREAD

**Issue by aranmohyeddin** [ambv/black#655]
Operating system: Archlinux
Python version: 3.7.1
*Black* version: 18.9b0

I have followed the guide and I use vim-Plug I have successfully installed the plugin and it works just fine.
then I do `workon mypersonalvenv` and after that if I wanna open vim it says:
```
$ vim main.py 
Error detected while processing /home/aran/.vim/plugged/black/plugin/black.vim:
line  124:
Traceback (most recent call last):
  File "<string>", line 56, in <module>
ModuleNotFoundError: No module named 'black'
Press ENTER or type command to continue
```
when I press enter and then run `:Black` I get:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> NameError: name 'Black' is not defined

when I run `:PlugInstall` it says:
`- black: Already installed `
 Also vim has created these files:
```
/home/aran/.vim/black
├── bin
│   ├── activate
│   ├── activate.csh
│   ├── activate.fish
│   ├── python
│   └── python3
├── include
├── lib
│   └── python3.7
│       └── site-packages
├── lib64 -> lib
└── pyvenv.cfg

6 directories, 6 files
```

**Comment by aranmohyeddin** [comment]
The problem was that I was already inside my personal environment when I ran :PlugInstall now I removed ~/.vim/black and deactivaded my venv and opened vim again(automatically installs black) and then did workon mypersonalvenv and it works just fine now.
