### ISSUE TITLE
EOFError while loading pickled grammar

### ISSUE THREAD

**Issue by asottile** [ambv/black#673]
This comes from a run of [blacken-docs](https://github.com/asottile/blacken-docs)

Unfortunately I don't have much more information or a reproduction than that.

The version this was using was `black==18.6b4` with python 3.6 -- I'll see if I can't reproduce on a newer version.

```
Traceback (most recent call last):
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/bin/blacken-docs", line 11, in <module>
    load_entry_point('blacken-docs==0.2.0', 'console_scripts', 'blacken-docs')()
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/blacken_docs.py", line 11, in <module>
    import black
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/black.py", line 76, in <module>
    pygram.initialize(CACHE_DIR)
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/blib2to3/pygram.py", line 42, in initialize
    cache_dir)
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/blib2to3/pgen2/driver.py", line 201, in load_packaged_grammar
    return load_grammar(grammar_source, gp=gp)
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/blib2to3/pgen2/driver.py", line 175, in load_grammar
    g.load(gp)
  File "/code/.cache/pre-commit/repocfztsymd/py_env-python3/lib/python3.6/site-packages/blib2to3/pgen2/grammar.py", line 95, in load
    d = pickle.load(f)
EOFError: Ran out of input
```

Upon retry this succeeded, seems to be flakey

**Comment by asottile** [comment]
My guess here is that the write of the cache file is not atomic and so with many processes attempting to write that there is a race where they collide?

**Comment by asottile** [comment]
Here's a ~reliable reproduction, against the latest version (my VM has 4 cpus)

```
touch {1..50}.py
ls *.py | xargs -P4 --replace bash -c 'rm -rf ~/.cache/black && black -q {}'
```

output:
```
$ ls *.py | xargs -P4 --replace bash -c 'rm -rf ~/.cache/black && black -q {}'
error: cannot format 42.py: Ran out of input
```

**Comment by asottile** [comment]
The workaround (when using `pre-commit`) for both `black` and `blacken-docs` until `black` makes a release is to [force serial mode](https://pre-commit.com/#new-hooks):

### black

```yaml
-   repo: https://github.com/ambv/black
    rev: ...
    hooks:
    -   id: black
        require_serial: true
```

### blacken-docs

```yaml
-   repo: https://github.com/asottile/blacken-docs
    rev: ...
    hooks:
    -   id: blacken-docs
        require_serial: true
```

**Comment by zsol** [comment]
FWIW I can still see this happening in our internal runs

**Comment by zsol** [comment]
Oh and that's because these runs are not using a version that has #674 yet. Will reopen if I still see this after applying #674
